language: python
python:
   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"
script:
   - python PythonProgram.py
services:
   - docker
before_install:
  - docker build -t kirtigupta123/py-Img .
  - docker images
