language: python

python:

  - "3.6"

script: 

  - python PythonProgram.py
notifications:
  email: Priyalguptaniec123@gmail.com
services:
  - docker
before_install:
  - docker build -t kirtigupta123/py-img .
  - docker images
  


