language: python
python:
   - "3.6"
   - "2.7"
   - "3.5"
script:
 - python PythonProgram.py
notifications:
  email: Priyalguptaniec123@gmail.com
services:
  - docker
before_install:
  - docker build -t kirtigupta123/py-image .
  - docker images
  - echo "$DockerPass" | docker login -u "$DockerID" --password-stdin
  - docker run -it --name mycontainer1 kirtigupta123/py-image 
  - docker push kirtigupta123/py-image
  - docker pull kirtigupta123/py-image
  - docker run -it --name mycontainer2 kirtigupta123/py-image  

  
  

  
